name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/azure-static-web-apps-lemon-moss-05d6e4c03.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build web
        working-directory: web
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "web"
          output_location: ""   
          api_location: ""          # CRITICAL: disables Managed API
