name: Deploy Python to Azure App Service
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      # deploy step goes here (uses publish profile/azure login), omitted until creds are ready
