name: deploy-functions

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-functions.yml'
  workflow_dispatch:

# Required for OIDC login
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_NAME: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
      AZURE_RESOURCE_GROUP:  ${{ vars.AZURE_RESOURCE_GROUP }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # OIDC-based login (no client secret needed)
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:        ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:        ${{ secrets.AZURE_TENANT_ID }}
          subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install production deps (Functions)
        working-directory: api
        run: npm ci --omit=dev

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name:     ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package:      ./api
          node-version: '20'
          slot-name:    Production
