name: deploy-functions

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-functions.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: functions-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_NAME: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
      AZURE_RESOURCE_GROUP:  ${{ vars.AZURE_RESOURCE_GROUP }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Ensure production dependencies are included in the package (Linux Consumption + Run-From-Package)
      - name: Install production deps
        working-directory: api
        run: npm ci --omit=dev

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name:  ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package:   ./api
          slot-name: Production
          # functions-action will call synctriggers for you; no extra az rest needed.

      # Optional: not required in most cases
      - name: Restart Function App (optional)
        run: az functionapp restart -g "${{ env.AZURE_RESOURCE_GROUP }}" -n "${{ env.AZURE_FUNCTIONAPP_NAME }}"
