name: Deploy SWA

on:
  push:
    branches: [ main, feat/** ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & build
        working-directory: web          # <-- change if your app folder is different
        run: |
          npm ci || npm install
          npm run build --if-present

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: web              # <-- path to your app source
          output_location: dist          # <-- built files relative to app_location
